### ISSUE TITLE
Point people towards a fork

### ISSUE THREAD

**Issue by skuzzymiglet** [brandonchartier/html#1]
Hi!

@swlkr [forked](https://github.com/swlkr/janet-html) this project, and added HTML escaping and other improvements.

Since so many people land here, it may be worthwhile directing them to the fork

**Comment by swlkr** [comment]
I could also merge but I changed so much of the code I wasn’t sure if I should

**Comment by brandonchartier** [comment]
Absolutely, I will update the README soon. Thanks for your work!
